export const actionType = {
  setCharacter: "setCharacter",
  setPet: "setPet",
  setLocation: "setLocation",
  setlocationError: "setlocationError",
  setlocationLoading: "setlocationLoading",
  setGifts: "setGifts",
  removeGift: "removeGift",
  setUser: "setUser",
  setMission: "setMission",
  setHatchery: "setHatchery",
  setTrailLocation: "setTrailLocation",
  setTrailIndex: "setTrailIndex",
  setTrailRandmarkIndex: "setTrailRandmarkIndex",
  setTodayWalk: "setTodayWalk",
};
