module.exports = {
  Character: require("./Character"),
  UserCharacter: require("./CharacterUser"),
  Egg: require("./Egg"),
  UserEgg: require("./EggUser"),
  Friend: require("./Friend"),
  Gift: require("./Gift"),
  Log: require("./Log"),
  Mission: require("./Mission"),
  UserMission: require("./MissionUser"),
  Pet: require("./Pet"),
  UserPet: require("./PetUser"),
  Reward: require("./Reward"),
  UserReward: require("./RewardUser"),
  Trail: require("./Trail"),
  UserTrail: require("./TrailUser"),
  Landmark: require("./Landmark"),
  User: require("./User"),
  Walk: require("./Walk"),
};
